'use client';

import './globals.css'
import { Inter } from 'next/font/google'
import { Provider } from "react-redux";
import {store} from '@/redux/store/store';
import { AppProviders } from '@/providers/providers';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next App, Redux Toolkit, Typescript, Jest',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
		<body className={inter.className}>
			<AppProviders>
				<Provider store={store}>
					{children}
				</Provider>
			</AppProviders>
		</body>
    </html>
  )
}
